name: Run tests
on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-20.04
    if: "!contains(toJSON(github.event.commits.*.message), 'ci:')"
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: npm test
